from setuptools import setup, find_namespace_packages

scm_version_template = """
# Generated by setuptools_scm

__all__ = ["__version__"]

__version__ = "{version}"

"""
install_requires = [""]
tests_require = ["pytest", "pytest-cov", "pytest-flake8"]
dev_requires = install_requires + tests_require + ["documenteer[pipelines]"]

setup(
    name="ts_athexapod",
    use_scm_version={"write_to": "python/lsst/ts/ATHexapod/version.py",
                     "write_to_template": scm_version_template},
    setup_requires=["setuptools_scm"],
    install_requires=install_requires,
    package_dir={"": "python"},
    packages=find_namespace_packages(where="python"),
    scripts=["bin/runATHexapodCSC.py"],
    tests_require=tests_require,
    extras_require={"dev": dev_requires},
    license="GPL"
)
